<?php

/**
 * @file
 * Provides menus, permissions and utilities to WHM Module.
 */

_whm_include('whm.api');

/**
 * Implements hook_permission().
 */
function whm_permission() {
  return array('administer whm settings');
}

/**
 * Implements hook_menu().
 */
function whm_menu() {
  $items['admin/whm'] = array(
    'title' => 'WHM',
    'description' => 'Configure the Web Hosting Manager integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_admin_settings'),
    'access arguments' => array('administer whm settings'),
    'file' => 'includes/whm.admin.inc',
    'position' => 'right',
    'weight' => 6,
  );
  $items['admin/whm/settings'] = array(
    'title' => 'Settings',
    'description' => 'Configure the Web Hosting Manager integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_admin_settings'),
    'access arguments' => array('administer whm settings'),
    'file' => 'includes/whm.admin.inc',
  );
  $items['admin/whm/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
  return $items;
}

/**
 * Implements hook_simpletest().
 */
function whm_simpletest() {
  $dir = drupal_get_path('module', 'whm') . '/tests';
  $tests = file_scan_directory($dir, '\.test$');
  return array_keys($tests);
}

/**
 * Include .inc files as necessary.
 */
function _whm_include($includes, $module = 'whm') {
  if (is_string($includes)) {
    $includes = array($includes);
  }
  static $used = array();
  foreach ($includes as $file) {
    if (!isset($used[$module][$file])) {
      require_once './' . drupal_get_path('module', $module) . "/includes/$file.inc";
    }
    $used[$module][$file] = TRUE;
  }
}

/**
 * Helper for dumping debug data nicely.
 */
function _whm_dump($data, $exit = TRUE) {
  print '<pre>';
  if (is_array($data)) {
    print_r($data);
  }
  elseif (is_object($data)) {
    var_dump($data);
  }
  else {
    print $data;
  }
  print '</pre>';
  if ($exit) {
    exit();
  }
}
