<?php

/**
 * @file
 * Provides a status overview for cPanel's 
 * WebHost Manager (WHM) server administration software.
 *
 * Allows administrators or authorized users to:
 * - View an overview of the WHM server's status.
 */

/**
 * Implements hook_permission().
 */
function whm_overview_permission() {
  return array(
    'view whm overview' => array(
      'title' => t('View WHM overview'),
      'description' => t('Can view the WHM overview.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function whm_overview_menu() {
  $items['admin/whm/overview'] = array(
    'title' => 'Overview',
    'description' => 'Show WHM server status overview.',
    'page callback' => 'whm_overview_overview_page',
    'access arguments' => array('view whm overview'),
    'file' => 'includes/whm.overview.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -1,
  );
  return $items;
}
