<?php

/**
 * @file
 * Provides user and programming interfaces to cPanel's 
 * WebHost Manager (WHM) server administration software.
 *
 * Allows administrators or authorized users to:
 * - create cPanel accounts as a reseller through WHM.
 * - list current cPanel accounts associated with reseller
 */

/**
 * Implements hook_permission().
 */
function whm_ui_permission() {
  return array(
    'list whm accounts' => array(
      'title' => t('List WHM accounts'),
      'description' => t('Can view a list of WHM accounts.'),
    ),
    'create whm accounts' => array(
      'title' => t('Create WHM accounts'),
      'description' => t('Can create WHM accounts.'),
      'restrict access' => TRUE,
    ),
    'edit whm accounts' => array(
      'title' => t('Edit WHM accounts'),
      'description' => t('Can edit WHM accounts.'),
      'restrict access' => TRUE,
    ),
    'suspend whm accounts' => array(
      'title' => t('Suspend WHM accounts'),
      'description' => t('Can suspend WHM accounts.'),
      'restrict access' => TRUE,
    ),
    'terminate whm accounts' => array(
      'title' => t('Terminate WHM accounts'),
      'description' => t('Can terminate WHM accounts.'),
      'restrict access' => TRUE,
    ),
    'list whm plans' => array(
      'title' => t('List WHM plans'),
      'description' => t('Can list WHM plans/packages.'),
      'restrict access' => TRUE,
    ),
    'create whm plans' => array(
      'title' => t('Create WHM plans'),
      'description' => t('Can create WHM plans/packages.'),
      'restrict access' => TRUE,
    ),
    'edit whm plans' => array(
      'title' => t('Edit WHM plans'),
      'description' => t('Can edit WHM plans/packages.'),
      'restrict access' => TRUE,
    ),
    'delete whm plans' => array(
      'title' => t('Delete WHM plans'),
      'description' => t('Can delete WHM plans/packages.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function whm_ui_menu() {
  $items['admin/whm/accounts'] = array(
    'title' => 'Accounts',
    'description' => 'List cPanel accounts managed by current reseller.',
    'page callback' => 'whm_ui_list_accounts_form',
    'access arguments' => array('list whm accounts'),
    'file' => 'includes/whm.ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/whm/accounts/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/whm/accounts/create'] = array(
    'title' => 'Add Account',
    'description' => 'Create new cPanel account from current reseller.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_create_account_form'),
    'access arguments' => array('create whm accounts'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/whm.ui.admin.inc',
    'weight' => 1,
  );
  $items['admin/whm/accounts/account/%/edit'] = array(
    'title' => 'Edit Account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_edit_account_form', 4),
    'access arguments' => array('edit whm accounts'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/whm.ui.admin.inc',
  );
  $items['admin/whm/accounts/account/%/suspend'] = array(
    'title' => 'Suspend',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_confirm_suspend_account', 4),
    'access arguments' => array('suspend whm accounts'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/whm.ui.admin.inc',
  );
  $items['admin/whm/accounts/account/%/unsuspend'] = array(
    'title' => 'Unsuspend',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_confirm_unsuspend_account', 4),
    'access arguments' => array('suspend whm accounts'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/whm.ui.admin.inc',
  );
  $items['admin/whm/accounts/account/%/terminate'] = array(
    'title' => 'Terminate',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_confirm_terminate_account', 4),
    'access arguments' => array('terminate whm accounts'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/whm.ui.admin.inc',
  );

  $items['admin/whm/plans'] = array(
    'title' => 'Plans',
    'description' => 'List cPanel plans managed by current reseller.',
    'page callback' => 'whm_ui_list_plans_form',
    'access arguments' => array('list whm plans'),
    'file' => 'includes/whm.ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/whm/plans/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/whm/plans/create'] = array(
    'title' => 'Add Plan',
    'description' => 'Create new cPanel plan form the current reseller.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_create_plan_form'),
    'access arguments' => array('create whm plans'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/whm.ui.admin.inc',
    'weight' => 1,
  );
  $items['admin/whm/plans/plan/%/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_edit_plan_form', 4),
    'access arguments' => array('edit whm plans'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/whm.ui.admin.inc',
  );
  $items['admin/whm/plans/plan/%/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whm_ui_confirm_delete_plan', 4),
    'access arguments' => array('delete whm plans'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/whm.ui.admin.inc',
  );

  return $items;
}
